#!/usr/bin/env bash

if [ -z "$WM_PROJECT" ]; then
  echo "OpenFOAM environment not found, forgot to source the OpenFOAM bashrc?"
  exit 1
fi

# test DAFoamIncompresible lib
rm -rf input
tar -xvf input.tar.gz
cd input/CurvedCubeHexMesh && cp -r 0.incompressible/* 0/ && decomposePar
cd ../../

cd DAFoamIncompressible && make && mpirun -np 4 python runTests.py || exit 1
cd ../

# test DAFoamCompressible lib
rm -rf input
tar -xvf input.tar.gz
cd input/CurvedCubeHexMesh && cp -r 0.compressible/* 0/ && decomposePar
cd ../../

cd DAFoamCompressible && make && mpirun -np 4 python runTests.py || exit 1
cd ../

# test DASimpleFoam
rm -rf input
tar -xvf input.tar.gz

cd pyDAFoam && mpirun -np 4 python runTests_DASimpleFoam.py || exit 1
cd ../

# test DARhoSimpleFoam
rm -rf input
tar -xvf input.tar.gz

cd pyDAFoam && mpirun -np 4 python runTests_DARhoSimpleFoam.py || exit 1
cd ../
