#!/usr/bin/env bash

if [ -z "$WM_PROJECT" ]; then
  echo "OpenFOAM environment not found, forgot to source the OpenFOAM bashrc?"
  exit 1
fi

rm -rf input
tar -xvf input.tar.gz
cd input/CurvedCubeHexMesh && decomposePar
cd ../../

cd DAFoamIncompressible && make && mpirun -np 4 python runTests.py
cd ../

cd pyDAFoam && python runTests.py
cd ../
