#!/usr/bin/env bash

if [ -z "$WM_PROJECT" ]; then
  echo "OpenFOAM environment not found, forgot to source the OpenFOAM bashrc?"
  exit 1
fi

if [ "$DAOF_AD_MODE" = "DAOF_AD_MODE_A1S" ]; then
  exit 0
elif [ "$DAOF_AD_MODE" = "DAOF_AD_MODE_A1S" ]; then
  exit 0
fi

for d in ./*/ ; do 
  cd "$d" 
  wmake
  cd ../
done
