#!/usr/bin/env bash

if [ -z "$WM_PROJECT" ]; then
  echo "OpenFOAM environment not found, forgot to source the OpenFOAM bashrc?"
  exit 1
fi


cd pyDASolverIncompressible
rm -rf build *.so *.cpp
cd ../

cd pyDASolverCompressible
rm -rf build *.so *.cpp
cd ../

