#!/usr/bin/env bash

if [ -z "$WM_PROJECT" ]; then
  echo "OpenFOAM environment not found, forgot to source the OpenFOAM bashrc?"
  exit 1
fi

cp setup_Incompressible.py setup.py
sed -i 's/"-std=c++11",/"-std=c++11","-DFULLDEBUG -g -O0",/g' setup.py
python setup.py build_ext --inplace 
mv *.so ../../

./Allclean

cp setup_Compressible.py setup.py
sed -i 's/"-std=c++11",/"-std=c++11","-DFULLDEBUG -g -O0",/g' setup.py
python setup.py build_ext --inplace 
mv *.so ../../
