#!/usr/bin/env bash

if [ -z "$WM_PROJECT" ]; then
  echo "OpenFOAM environment not found, forgot to source the OpenFOAM bashrc?"
  exit 1
fi

cd DASolver
./Allmake_Incompressible_Opt
./Allclean
./Allmake_Compressible_Opt
cd ../

cd pyDASolverIncompressible
python setup.py build_ext --inplace 
mv *.so ../../
cd ../

cd pyDASolverCompressible
python setup.py build_ext --inplace 
mv *.so ../../
cd ../
