#!/usr/bin/env bash

if [ -z "$WM_PROJECT" ]; then
  echo "OpenFOAM environment not found, forgot to source the OpenFOAM bashrc?"
  exit 1
fi

for d in ./*/ ; do 
  cd "$d"
  sed -i 's/"-std=c++11",/"-std=c++11","-DFULLDEBUG -g -O0",/g' setup.py
  python setup.py build_ext --inplace 
  mv *.so ../../
  sed -i 's/"-std=c++11","-DFULLDEBUG -g -O0",/"-std=c++11",/g' setup.py 
  cd ../
done